# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Sun Feb 27 15:51:34 2011

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class FRConfigFrame(wx.Dialog):
    def __init__(self, parent):
        # begin wxGlade: FRConfigFrame.__init__
        #kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Dialog.__init__(self, parent)
        self.title_label = wx.StaticText(self, -1, "Configuration Settings for\nFull Record Mode")
        self.static_line_3 = wx.StaticLine(self, -1)
        self.file_size_radio_box = wx.RadioBox(self, -1, "Maximum File Size", choices=["Record Until Out of Disk Space", "Record Until Specified File Size is Reached"], majorDimension=0, style=wx.RA_SPECIFY_ROWS)
        self.file_label = wx.StaticText(self, -1, "File Size (MB):")
        self.spin_ctrl_1 = wx.SpinCtrl(self, -1, "", min=1, max=1000000)
        self.plot_checkbox = wx.CheckBox(self, -1, "Display Waterfall Plot?")
        self.save_button = wx.Button(self, -1, "Save")
        self.cancel_button = wx.Button(self, -1, "Cancel")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

        self.Bind(wx.EVT_BUTTON, self.OnCancel, self.cancel_button)
        self.Bind(wx.EVT_BUTTON, self.OnSave, self.save_button)


    def __set_properties(self):
        # begin wxGlade: FRConfigFrame.__set_properties
        self.SetTitle("frame_5")
        self.title_label.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.file_size_radio_box.SetSelection(0)
        self.plot_checkbox.SetValue(1)
        self.save_button.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: FRConfigFrame.__do_layout
        sizer_7 = wx.BoxSizer(wx.VERTICAL)
        sizer_8 = wx.BoxSizer(wx.VERTICAL)
        sizer_9 = wx.BoxSizer(wx.VERTICAL)
        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8.Add(self.title_label, 0, wx.ALL, 10)
        sizer_8.Add(self.static_line_3, 0, wx.EXPAND, 0)
        sizer_9.Add(self.file_size_radio_box, 0, wx.ALL, 5)
        sizer_10.Add(self.file_label, 0, wx.LEFT|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 22)
        sizer_10.Add(self.spin_ctrl_1, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 8)
        sizer_9.Add(sizer_10, 1, wx.EXPAND, 0)
        sizer_9.Add(self.plot_checkbox, 0, wx.LEFT, 10)
        sizer_11.Add(self.save_button, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 15)
        sizer_11.Add(self.cancel_button, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 15)
        sizer_9.Add(sizer_11, 1, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_8.Add(sizer_9, 1, wx.EXPAND, 0)
        sizer_7.Add(sizer_8, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_7)
        sizer_7.Fit(self)
        self.Layout()
        # end wxGlade

    def OnCancel(self, event):
        self.EndModal(wx.ID_CANCEL)
        event.Skip()


    def OnSave(self, event):
        self.EndModal(wx.ID_OK)
        event.Skip()

# end of class FRConfigFrame


