function Hd = decimate_by_4
%DECIMATE_BY_4 Returns a discrete-time filter object.

%
% M-File generated by MATLAB(R) 7.6 and the Signal Processing Toolbox 6.9.
%
% Generated on: 20-Jul-2011 17:30:27
%

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in MHz.
Fs = 25;  % Sampling Frequency

N     = 12;    % Order
Fpass = 2;     % Passband Frequency
Fstop = 5;     % Stopband Frequency
Wpass = 1;     % Passband Weight
Wstop = 1000;  % Stopband Weight
dens  = 16;    % Density Factor

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Wpass Wstop], ...
           {dens});
Hd = dfilt.dffir(b);

% [EOF]
